12 social networks login page
VE-Stack/linked-resume pull request #14
Opened 2023-01-28 06:44 UTC by elnurastanov

2023-01-28 14:40 UTC, MDReal32 commented on src/components/background/index.tsx
> +import LinkedInIcon from "@mui/icons-material/LinkedIn";
Likely import order.

packages form node_modules
absolute packages by root
relative packages
icons/csss

empty line between them and react must be first like core package

2023-01-28 14:41 UTC, MDReal32 commented on src/components/background/index.tsx
> +    <Box
recomendable move to component and to scss file. (for easy writing)

2023-01-28 14:42 UTC, MDReal32 commented on src/components/icons/social.tsx
> +export const Social = ({ viewBox = "0 0 478.67 383.237", ...props }) => {
type of props.

if same as SvhIcon then use like `FC<{ imported typeof SvgIcon props }>`

2023-01-28 14:43 UTC, MDReal32 commented on src/components/steps/customStepConnector.ts
> +export const CustomStepConnector = styled(StepConnector)(({ theme }) => ({
I prefer separated scss file

2023-01-28 14:44 UTC, MDReal32 commented on src/constants/steps.ts
> +    label: "Select template ",
space on end of string

2023-01-28 14:45 UTC, MDReal32 commented on src/components/steps/index.tsx
> +      {Children.toArray(
useless call of `Children.toArray`

2023-01-28 14:55 UTC, MDReal32 requested changes
.

2023-01-28 16:30 UTC, elnurastanov commented on src/components/steps/index.tsx
> +      {Children.toArray(
Why? Children.toArray method prevents use key for each element and other performance issues

2023-01-28 16:34 UTC, elnurastanov commented on src/components/steps/customStepConnector.ts
> +export const CustomStepConnector = styled(StepConnector)(({ theme }) => ({
Separated scss file can’t provide theme property. This writing style recommended on material ui documentation

2023-01-28 16:36 UTC, elnurastanov commented on src/components/background/index.tsx
> +import LinkedInIcon from "@mui/icons-material/LinkedIn";
Auto import issue 😅

2023-01-29 06:59 UTC, MDReal32 commented on src/components/steps/index.tsx
> +      {Children.toArray(
okay

2023-01-29 07:00 UTC, MDReal32 commented on src/components/steps/customStepConnector.ts
> +export const CustomStepConnector = styled(StepConnector)(({ theme }) => ({
okay. I get u.

2023-01-30 12:23 UTC, MDReal32 approved these changes

2023-01-30 12:24 UTC, MDReal32 approved these changes
There is no commits but ok.

2023-01-31 12:44 UTC, merged